# Referee-Playstyle-Discipline Analytics Configuration

# Default competitions and seasons for analysis
default_analysis:
  competitions:
    - competition_id: 11  # La Liga
      season_id: 90      # 2020/21
    - competition_id: 2   # Premier League
      season_id: 44      # 2020/21
    - competition_id: 16  # UEFA Euro
      season_id: 55      # 2024
    - competition_id: 43  # FIFA World Cup
      season_id: 3       # 2018

# Feature engineering parameters
features:
  playstyle:
    # Pressing & Block features
    ppda_threshold: 10.0
    defensive_thirds:
      defensive: [0, 40]
      middle: [40, 80] 
      attacking: [80, 120]
    
    # Possession & Directness
    long_pass_threshold: 30.0  # meters
    
    # Channels & Delivery (field width = 80m)
    channels:
      left: [0, 26.67]
      center: [26.67, 53.33]
      right: [53.33, 80]
    
    # Transitions
    counter_patterns:
      - "From Counter"
      - "From Throw In"

  discipline:
    # Spatial zones configuration
    zones:
      x_bins: 5  # 5 zones across 120m field length
      y_bins: 3  # 3 zones across 80m field width
    
    # Card handling
    card_treatment: "separate"  # "separate" or "cumulative" for Second Yellow
    
    # Minimum event thresholds
    min_events:
      match_events: 100
      team_passes: 50
      foul_locations: 1

# Modeling parameters
modeling:
  zone_nb:
    # Negative Binomial GLM settings
    exposure_offset: "log_opp_passes"  # or "log_minutes"
    alpha: 0.05  # significance level
    
    # Feature standardization
    standardize_features: true
    
    # Core interaction features (limit to avoid overfitting)
    interaction_features:
      - "directness"
      - "ppda"
    
    # Minimum data requirements
    min_referee_matches: 5
    min_zone_events: 3

# Export/storage paths
paths:
  data_dir: "data"
  models_dir: "data/models_nb_zone"
  figures_dir: "data/figs"
  exports_dir: "data/exports"

# Visualization settings
visualization:
  heatmap:
    field_dimensions:
      length: 120
      width: 80
    color_scheme: "RdYlBu_r"
    significance_alpha: 0.05
  
  forest_plot:
    confidence_level: 0.95
    max_referees_display: 15
    
# CLI settings
cli:
  default_competitions: [11, 2, 16, 43]
  batch_size: 10  # matches to process in parallel
  cache_events: true
  verbose: true

# Archetype categorization thresholds (research-based)
archetype_thresholds:
  pressing:
    very_high:
      ppda: [0, 8]  # exclusive upper bound
      def_share_att_third: [0.40, 1.0]
    high:
      ppda: [8, 12]  # exclusive upper bound  
      def_share_att_third: [0.25, 0.40]  # exclusive upper bound
    mid:
      ppda: [12, 18]  # exclusive upper bound
      def_share_att_third: [0.15, 0.25]  # exclusive upper bound
    low:
      ppda: [18, float('inf')]
      def_share_att_third: [0.00, 0.15]  # exclusive upper bound
  
  block:
    high:
      block_height_x: [70, 120]
    mid:
      block_height_x: [45, 70]  # exclusive upper bound
    low:
      block_height_x: [0, 45]  # exclusive upper bound
  
  possession_directness:
    possession_based:
      possession_share: [0.55, 1.0]
      directness: [0.00, 0.40]  # exclusive upper bound
    balanced:
      possession_share: [0.45, 0.55]  # exclusive upper bound
      directness: [0.40, 0.60]  # exclusive upper bound
    direct:
      possession_share: [0.00, 0.45]  # exclusive upper bound
      directness: [0.60, 1.0]
  
  width:
    wing_overload:
      wing_share: [0.75, 1.0]
      cross_share: [0.05, 1.0]  # Updated based on research
    central_focus:
      wing_share: [0.00, 0.60]  # exclusive upper bound
      lane_center_share: [0.30, 1.0]  # Updated threshold
    balanced_channels:
      wing_share: [0.60, 0.75]  # exclusive upper bound
      lane_center_share: [0.20, 0.30]  # exclusive upper bound
  
  transition:
    very_high:
      counter_rate: [0.25, 1.0]  # New very high category
    high:
      counter_rate: [0.15, 0.25]  # exclusive upper bound
    medium:
      counter_rate: [0.10, 0.15]  # exclusive upper bound
    low:
      counter_rate: [0.00, 0.10]  # exclusive upper bound
  
  overlays:
    cross_heavy:
      cross_share: [0.05, 1.0]  # Updated from research (was 0.12)
    set_piece_focus:
      fouls_committed: [0, 9]  # Updated from research (was 8)
    high_press_tactical_stops:
      foul_share_att_third: [0.10, 1.0]  # New overlay
    central_leaning:
      lane_center_share: [0.30, 1.0]  # New overlay
    sustained_low_block:
      foul_share_def_third: [0.55, 1.0]  # New overlay
    long_shot_heavy:
      shots_outside_box_share: [0.50, 1.0]  # New overlay (when available)
  
  # Supporting metrics for detailed analysis (metadata only)
  supporting_metrics:
    pass_length:
      short: [0, 17]
      medium: [17, 22]
      long: [22, float('inf')]
    long_pass_share:
      low: [0, 0.08]
      mid: [0.08, 0.15]
      high: [0.15, 1.0]
    forward_pass_share:
      low: [0, 0.35]
      mid: [0.35, 0.45]
      high: [0.45, 1.0]
    passes_per_possession:
      direct: [0, 3]
      balanced: [3, 6]
      patient: [6, float('inf')]
    xg_mean:
      low_quality: [0, 0.10]
      average: [0.10, 0.15]
      high_quality: [0.15, 1.0]
    discipline:
      fouls_per_opp_pass:
        low: [0, 0.020]
        mid: [0.020, 0.030]
        high: [0.030, 1.0]
      yellows_per_match:
        low: [0, 1.5]
        high: [2.0, 10.0]